ht_werke/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    # url(r'^administracija/', include('projects.urls')),
    url(r'^', include('projects.urls')), # posle je moguce ubaciti sajt na ovoj adresi, druga aplikacija
]
admin.site.site_header = "HT WERKE admin"

projects/urls.py
from django.conf.urls import url
from . import views


app_name = 'projects'

urlpatterns = [
    url(r'^$', views.sajt, name='sajt'),
    url(r'^administracija/$', views.index, name='index'),
    url(r'^administracija/radnici/$', views.ljudi, name='ljudi'),
    url(r'^administracija/vozila/$', views.vozila, name='vozila'),
    url(r'^administracija/login_user/$', views.login_user, name='login_user'),
    url(r'^administracija/logout_user/$', views.logout_user, name='logout_user'),
    url(r'^administracija/novi_projekat/$', views.create_project, name='project-add'),
    url(r'^administracija/mesecni_pregled_radnika/(?P<mesec>[0-9]+)/(?P<godina>[0-9]+)/(?P<posao_id>[a-zA-Z0-9_.-]+)$', views.mesecni_izvod_radnika, name='monthview-workers'),  # samo string (?P<posao>[\w\-]+)
    url(r'^administracija/mesecni_pregled_pojedinca/(?P<mesec>[0-9]+)/(?P<godina>[0-9]+)/(?P<radnik_id>[0-9]+)/(?P<posao_id>[a-zA-Z0-9_.-]+)$', views.mesecni_izvod_single, name='monthview-single'),
    url(r'^administracija/mesecni_pregled_poslova/(?P<od_meseca>[0-9]+)/(?P<do_meseca>[0-9]+)/(?P<godina>[0-9]+)$', views.mesecni_izvod_poslova, name='monthview-projects'),
    url(r'^administracija/posao/(?P<project_id>[0-9]+)/$', views.detail, name='posao'),
    url(r'^administracija/radnik/(?P<radnik_id>[0-9]+)/$', views.radnik_detail, name='radnik-detail'),
    url(r'^administracija/vozilo/(?P<vozilo_id>[0-9]+)/$', views.vozilo_detail, name='vozilo-detail'),
    url(r'^administracija/komentar/(?P<komentar_id>[0-9]+)/$', views.komentar_detail, name='komentar-detail'),
    url(r'^administracija/komentar_vozilo/(?P<komentar_id>[0-9]+)/$', views.komentar_vozilo_detail, name='komentar_za_vozilo-detail'),
    url(r'^administracija/azuriranje_posla/(?P<project_id>[0-9]+)/$', views.posao_update, name='posao-update'),
    url(r'^administracija/azuriranje_radnika/(?P<radnik_id>[0-9]+)/$', views.radnik_update, name='radnik-update'),
    url(r'^administracija/azuriranje_dana/(?P<dan_id>[0-9]+)/(?P<posao_id>[a-zA-Z0-9_.-]+)$', views.dan_update, name='dan-update'),
    url(r'^administracija/azuriranje_akontacije/(?P<mesec>[0-9]+)/(?P<godina>[0-9]+)/(?P<posao_id>[a-zA-Z0-9_.-]+)/(?P<akontacija_id>[0-9]+)$', views.akontacija_update, name='akontacija-update'),
    url(r'^administracija/azuriranje_licnog_dohodka/(?P<mesec>[0-9]+)/(?P<godina>[0-9]+)/(?P<posao_id>[a-zA-Z0-9_.-]+)/(?P<ld_id>[0-9]+)$', views.licni_dohodak_update, name='licni_dohodak-update'),
    url(r'^administracija/azuriranje_vozila/(?P<vozilo_id>[0-9]+)/$', views.vozilo_update, name='vozilo-update'),
    url(r'^administracija/izmena_komentara/(?P<komentar_id>[0-9]+)/$', views.komentar_update, name='komentar-update'),
    url(r'^administracija/izmena_komentara_vozilo/(?P<komentar_id>[0-9]+)/$', views.komentar_vozilo_update, name='komentar_vozilo-update'),
    url(r'^administracija/novi_prihod/(?P<project_id>[0-9]+)/$', views.create_prihod, name='prihod-add'),
    url(r'^administracija/novi_rashod/(?P<project_id>[0-9]+)/$', views.create_rashod, name='rashod-add'),
    url(r'^administracija/novi_kvadrati/(?P<project_id>[0-9]+)/$', views.create_kvadrat, name='kvadrat-add'),
    url(r'^administracija/novi_komentar/(?P<project_id>[0-9]+)/$', views.create_komentar, name='komentar-add'),
    url(r'^administracija/novi_komentar_vozilo/(?P<vozilo_id>[0-9]+)/$', views.create_vozilo_komentar, name='komentar_vozilo-add'),
    url(r'^administracija/novo_zanimanje/$', views.create_zanimanje, name='zanimanje-add'),
    url(r'^administracija/novi_radnik/$', views.create_radnik, name='radnik-add'),
    url(r'^administracija/novo_vozilo/$', views.create_vozilo, name='vozilo-add'),
    url(r'^administracija/posao/(?P<project_id>[0-9]+)/obrisi_prihod/(?P<prihod_id>[0-9]+)/$', views.prihod_delete, name='prihod-delete'),
    url(r'^administracija/(?P<project_id>[0-9]+)/obrisi_rashod/(?P<rashod_id>[0-9]+)/$', views.rashod_delete, name='rashod-delete'),
    url(r'^administracija/(?P<project_id>[0-9]+)/obrisi_komentar/(?P<komentar_id>[0-9]+)/$', views.komentar_delete, name='komentar-delete'),
    url(r'^administracija/(?P<vozilo_id>[0-9]+)/obrisi_komentar_vozilo/(?P<komentar_id>[0-9]+)/$', views.komentar_vozilo_delete, name='komentar_za_vozilo-delete'),
    url(r'^administracija/obrisi_posao/(?P<posao_id>[0-9]+)/$', views.posao_delete, name='posao-delete'),
    url(r'^administracija/obrisi_radnika/(?P<radnik_id>[0-9]+)/$', views.radnik_delete, name='radnik-delete'),
    url(r'^administracija/obrisi_vozilo/(?P<vozilo_id>[0-9]+)/$', views.vozilo_delete, name='vozilo-delete'),
    url(r'^administracija/biranje_meseca/$', views.biranje_meseca, name='biranje_meseca'),
    url(r'^administracija/biranje_meseca_finansije/$', views.biranje_meseca_za_finansije, name='biranje_meseca_finansije'),
    url(r'^administracija/dodaj_dane/(?P<mesec>[0-9]+)/(?P<godina>[0-9]+)/(?P<posao_id>[a-zA-Z0-9_.-]+)$', views.dodaj_dane, name='dodaj_dane'),
    url(r'^administracija/pdf/(?P<posao_id>[0-9]+)$', views.pdf_posao, name='pdf_posao'),
    url(r'^administracija/pdf_radnik/(?P<radnik_id>[0-9]+)$', views.pdf_radnik, name='pdf_radnik'),
    url(r'^administracija/pdf_radnici_mesecni_izvestaj/(?P<mesec>[0-9]+)/(?P<godina>[0-9]+)/(?P<posao_id>[a-zA-Z0-9_.-]+)$', views.pdf_radnici_mesecni_izvestaj, name='pdf_radnici_mesecni_izvestaj'),
    url(r'^administracija/pdf_posao_mesecni_izvestaj/(?P<posao_id>[0-9]+)/(?P<mesec>[0-9]+)/(?P<godina>[0-9]+)/$', views.pdf_posao_mesecni_presek, name='pdf_posao_mesecni')
]

projects/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals
from django.db import models


class Poslovi(models.Model):
    ime = models.CharField(max_length=30)
    opis = models.CharField(max_length=100, blank=True)
    dogovoreni_radni_sati = models.FloatField(default=0.0)
    dogovoreni_radni_sati_klasa_2 = models.FloatField(default=0.0)
    dogovoreni_radni_sati_klasa_3 = models.FloatField(default=0.0)
    dogovoreni_radni_sati_klasa_4 = models.FloatField(default=0.0)
    dogovoreni_radni_sati_klasa_5 = models.FloatField(default=0.0)
    dogovoreno_po_kvadratu = models.FloatField(default=0.0)
    pocetak_radova = models.DateField()
    kraj_radova = models.DateField(null=True, blank=True)

    def __unicode__(self):
        return self.ime

    class Meta:
        verbose_name_plural = "Poslovi"


class Zanimanja(models.Model):
    zanimanje = models.CharField(max_length=30)

    def __unicode__(self):
        return self.zanimanje

    class Meta:
        verbose_name_plural = "Zanimanja"

klase = (
    ('klasa_1', 'KLASA 1'),
    ('klasa_2', 'KLASA 2'),
    ('klasa_3', 'KLASA 3'),
    ('klasa_4', 'KLASA 4'),
    ('klasa_5', 'KLASA 5'),
)


class Radnik(models.Model):
    ime = models.CharField(max_length=50)
    oib = models.CharField(max_length=50, null=True, blank=True)
    datum_rodjenja = models.CharField(max_length=10, null=True, blank=True)
    prebivaliste = models.CharField(max_length=30, null=True, blank=True)
    broj_telefona = models.CharField(max_length=30, blank=True)
    broj_odela = models.IntegerField(default=None, null=True, blank=True)
    broj_cipela = models.IntegerField(default=None, null=True, blank=True)
    poceo_raditi = models.DateField(null=True, blank=True)
    ugovor_vazi_do = models.DateField(null=True, blank=True)
    satnica = models.FloatField(max_length=10)
    zaduzena_oprema = models.CharField(max_length=100, blank=True)
    dostupan = models.BooleanField(default=True)
    posao = models.ForeignKey(Poslovi, null=True, blank=True, on_delete=models.SET_NULL)
    u_radnom_odnosu = models.BooleanField(default=True)
    klasa = models.CharField(max_length=10, choices=klase, default='klasa_1')
    zanimanja = models.ManyToManyField(Zanimanja)
    dana_do_isteka_ugovora = models.IntegerField(default=None, null=True, blank=True)
    komentar = models.CharField(max_length=500, blank=True)

    def __unicode__(self):
        return self.ime

    class Meta:
        verbose_name_plural = "Radnici"


class Vozilo(models.Model):
    marka = models.CharField(max_length=30)
    registracija = models.CharField(max_length=30, null=True, blank=True)
    predjeni_kilometri = models.CharField(max_length=50, null=True, blank=True)
    registracija_istice = models.DateField()
    sledeci_servis = models.CharField(max_length=50, null=True, blank=True)
    potrosnja_goriva = models.FloatField(max_length=10, default=0.0)
    opis = models.CharField(max_length=100, blank=True)
    trenutno_duzi = models.ForeignKey(Radnik, null=True, blank=True, on_delete=models.SET_NULL)

    def __unicode__(self):
        return self.marka

    class Meta:
        verbose_name_plural = "Vozila"


class Dan(models.Model):
    datum = models.DateField()
    radnik = models.ForeignKey(Radnik, on_delete=models.CASCADE)
    posao = models.ForeignKey(Poslovi, null=True, blank=True, on_delete=models.SET_NULL)
    radio_sati = models.FloatField(max_length=10, default=0.0)
    ishrana = models.FloatField(max_length=10, default=0.0)
    smestaj = models.FloatField(max_length=10, default=0.0)
    bolovanje = models.BooleanField(default=False)
    dozvoljeno_odsustvo = models.BooleanField(default=False)
    nedozvoljeno_odsustvo = models.BooleanField(default=False)
    doprinos = models.FloatField(max_length=10, default=0.0)
    doprinos_dodat = models.BooleanField(default=False)

    def __unicode__(self):
        return str(self.datum) + " - " + self.radnik.ime

    class Meta:
        verbose_name_plural = "Dani"


class Prihodi(models.Model):
    datum = models.DateField()
    vrsta = models.CharField(max_length=150)
    kolicina = models.FloatField(max_length=10, default=0.0)
    posao = models.ForeignKey(Poslovi, on_delete=models.CASCADE)

    def __unicode__(self):
        return self.vrsta

    class Meta:
        verbose_name_plural = "Prihodi"


class Rashodi(models.Model):
    datum = models.DateField()
    vrsta = models.CharField(max_length=150)
    kolicina = models.FloatField(max_length=10, default=0.0)
    posao = models.ForeignKey(Poslovi, on_delete=models.CASCADE)
    vozilo = models.ForeignKey(Vozilo, null=True, blank=True, on_delete=models.SET_NULL)

    def __unicode__(self):
        return self.vrsta

    class Meta:
        verbose_name_plural = "Rashodi"


class Akontacije(models.Model):
    godina = models.IntegerField()
    mesec = models.IntegerField()
    kolicina = models.FloatField(default=0.0)
    radnik = models.ForeignKey(Radnik)

    def __unicode__(self):
        return self.radnik.ime

    class Meta:
        verbose_name_plural = "Akontacije"

class RucnoLD(models.Model):
    godina = models.IntegerField()
    mesec = models.IntegerField()
    kolicina = models.FloatField(default=0.0)
    radnik = models.ForeignKey(Radnik)
    komentar = models.CharField(max_length=150, null=True, blank=True)

    def __unicode__(self):
        return self.radnik.ime

    class Meta:
        verbose_name_plural = "RucnoLD"

class Komentar(models.Model):
    datum = models.DateField(null=True, blank=True)
    komentar = models.TextField()
    posao = models.ForeignKey(Poslovi, on_delete=models.CASCADE)

    def __unicode__(self):
        return str(self.posao)

    class Meta:
        verbose_name_plural = "Komentari"

class Komentar_za_vozilo(models.Model):
    datum = models.DateField(null=True, blank=True)
    komentar_vozilo = models.TextField()
    vozilo = models.ForeignKey(Vozilo, on_delete=models.CASCADE)

    def __unicode__(self):
        return str(self.vozilo)

    class Meta:
        verbose_name_plural = "Komentari_za_vozila"

class Doprinos(models.Model):
    iznos = models.FloatField()

    class Meta:
        verbose_name_plural = "Doprinosi"

projects/forms.py
from django import forms
from django.contrib.auth.models import User
from .models import Poslovi, Vozilo, Radnik, Prihodi, Rashodi, Dan, Zanimanja, Akontacije, Komentar, RucnoLD, Komentar_za_vozilo

class DateInput(forms.DateInput):
    input_type = 'date'

class UserForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput)

    class Meta:
        model = User
        fields = ['username', 'password']

class ZanimanjeForm(forms.ModelForm):
    class Meta:
        model = Zanimanja
        fields = ['zanimanje']

class PosloviForm(forms.ModelForm):
    pocetak_radova = forms.DateField(
        widget=forms.DateInput(format='%d.%m.%Y', attrs={'class': "datum"}),
        input_formats=('%d.%m.%Y', '%d/%m/%Y', '%d.%m.%y', '%d/%m/%y'))
    kraj_radova = forms.DateField(
        widget=forms.DateInput(format='%d.%m.%Y', attrs={'class': "datum"}),
        input_formats=('%d.%m.%Y', '%d/%m/%Y', '%d.%m.%y', '%d/%m/%y'),
        required=False)
    class Meta:
        model = Poslovi
        fields = ['ime', 'opis', 'dogovoreni_radni_sati', 'dogovoreni_radni_sati_klasa_2', 'dogovoreni_radni_sati_klasa_3', 'dogovoreni_radni_sati_klasa_4', 'dogovoreni_radni_sati_klasa_5', 'dogovoreno_po_kvadratu', 'pocetak_radova', 'kraj_radova']

class RadnikForm(forms.ModelForm):
    poceo_raditi = forms.DateField(
        widget=forms.DateInput(format='%d.%m.%Y', attrs={'class': "datum"}), input_formats=('%d.%m.%Y', '%d/%m/%Y', '%d.%m.%y', '%d/%m/%y'))
    ugovor_vazi_do = forms.DateField(
        widget=forms.DateInput(format='%d.%m.%Y', attrs={'class': "datum"}), input_formats=('%d.%m.%Y', '%d/%m/%Y', '%d.%m.%y', '%d/%m/%y'))
    class Meta:
        model = Radnik
        fields = ['ime', 'oib', 'datum_rodjenja', 'prebivaliste', 'poceo_raditi', 'ugovor_vazi_do', 'satnica', 'broj_telefona', 'broj_odela', 'broj_cipela', 'zaduzena_oprema', 'zanimanja', 'u_radnom_odnosu', 'klasa', 'komentar']
        widgets = {
            'zanimanja': forms.CheckboxSelectMultiple,
            'komentar': forms.Textarea
        }

class VoziloForm(forms.ModelForm):
    registracija_istice = forms.DateField(
        widget=forms.DateInput(format='%d.%m.%Y', attrs={'class': "datum"}), input_formats=('%d.%m.%Y', '%d/%m/%Y', '%d.%m.%y', '%d/%m/%y'))
    class Meta:
        model = Vozilo
        fields = ['marka', 'registracija', 'predjeni_kilometri', 'registracija_istice', 'sledeci_servis', 'potrosnja_goriva', 'trenutno_duzi', 'opis']
        widgets = {
            'opis': forms.Textarea
        }

class RadnikForm__old(forms.ModelForm):
    class Meta:
        model = Radnik
        fields = ['ime', 'oib', 'poceo_raditi', 'ugovor_vazi_do', 'satnica', 'broj_telefona', 'broj_odela', 'broj_cipela', 'zaduzena_oprema', 'zanimanja']
        widgets = {
            'poceo_raditi': DateInput(),
            'ugovor_vazi_do': DateInput(),
            'zanimanja': forms.CheckboxSelectMultiple
        }

class PrihodiForm(forms.ModelForm):
    datum = forms.DateField(
        widget=forms.DateInput(format='%d.%m.%Y', attrs={'class': "datum"}),
        input_formats=('%d.%m.%Y', '%d/%m/%Y', '%d.%m.%y', '%d/%m/%y'))
    class Meta:
        model = Prihodi
        fields = ['datum', 'vrsta', 'kolicina']

class RashodiForm(forms.ModelForm):
    datum = forms.DateField(
        widget=forms.DateInput(format='%d.%m.%Y', attrs={'class': "datum"}),
        input_formats=('%d.%m.%Y', '%d/%m/%Y', '%d.%m.%y', '%d/%m/%y'))
    class Meta:
        model = Rashodi
        fields = ['datum', 'vrsta', 'kolicina', 'vozilo']


class KvadratForm(forms.Form):
    datum = forms.DateField(
        widget=forms.DateInput(format='%d.%m.%Y', attrs={'class': "datum"}),
        input_formats=('%d.%m.%Y', '%d/%m/%Y', '%d.%m.%y', '%d/%m/%y'))
    kolicina = forms.FloatField(label="kolicina")


class DatumForm(forms.Form):
    mesec = forms.IntegerField(max_value=12, min_value=1)
    godina = forms.IntegerField(label="godina")
    posao = forms.ModelChoiceField(queryset=Poslovi.objects.all(), required=False)

class Datum_finansForm(forms.Form):
    od_meseca = forms.IntegerField(max_value=12, min_value=1, required=False)
    do_meseca = forms.IntegerField(max_value=12, min_value=1, required=False)
    godina = forms.IntegerField(label="godina")

class DanForm(forms.ModelForm):
    class Meta:
        model = Dan
        fields = ['radio_sati', 'ishrana', 'smestaj', 'bolovanje', 'dozvoljeno_odsustvo', 'nedozvoljeno_odsustvo', 'doprinos_dodat']

class AkontacijeForm(forms.ModelForm):
    class Meta:
        model = Akontacije
        fields = ['kolicina']

class KomentarForm(forms.ModelForm):
    datum = forms.DateField(
        widget=forms.DateInput(format='%d.%m.%Y', attrs={'class': "datum"}),
        input_formats=('%d.%m.%Y', '%d/%m/%Y', '%d.%m.%y', '%d/%m/%y'),
        required=False)
    class Meta:
        model = Komentar
        fields = ['datum', 'komentar']

class Komentar_za_voziloForm(forms.ModelForm):
    datum = forms.DateField(
        widget=forms.DateInput(format='%d.%m.%Y', attrs={'class': "datum"}),
        input_formats=('%d.%m.%Y', '%d/%m/%Y', '%d.%m.%y', '%d/%m/%y'),
        required=False)
    class Meta:
        model = Komentar_za_vozilo
        fields = ['datum', 'komentar_vozilo']

class RucnoLDForm(forms.ModelForm):
    class Meta:
        model = RucnoLD
        fields = ['kolicina', 'komentar']

projects/templates/projects/form_template.html
{% for field in form %}

    <div class="form-group">
        <div class="col-sm-offset-2 col-sm-10">
            <span class="text-danger small">{{ field.errors }}</span>
        </div>
        <label class="control-label col-sm-2">{{ field.label_tag }}</label>
        <div class="col-sm-10">{{ field }}</div>
    </div>

{% endfor %}

projects/templates/projects/komentar_detalji.html
{% extends 'projects/base.html' %}
{% block title %} - Komentar {% endblock %}
{% block projects_active %}active{% endblock %}
{% block content %}

<div class="container">
    <div class="row">
    {% if messages %}
    <ul class="messages">
        {% for message in messages %}
        <li style="color:red;" {% if message.tags == "success" %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
        {% endfor %}
    </ul>
    {% endif %}
    </div>
    <div class="row">
        <h3> Komentar za {{ komentar.posao.ime }}
            <a href="{% url 'projects:komentar-update' komentar.id %}">
                <button type="button" class="btn btn-primary">
                    <span class="glyphicon glyphicon-pencil"></span>&nbsp; Izmeni komentar
                </button>
            </a>
        </h3>
        <h3>{{ komentar.datum }}</h3>
        <h4>{{ komentar.komentar }}</h4>
    </div>
</div>
{% endblock %}

projects/templates/projects/ljudi.html
{% extends 'projects/base.html' %}
{% block title %} - Ljudi {% endblock %}
{% block content %}
{% load staticfiles %}

{% load widget_tweaks %}

<div class="container">
    <h3>Radnici</h3>
    {% if messages %}
    <ul class="messages">
    {% for message in messages %}
    <li {% if message.tags == "success" %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
    {% endfor %}
    </ul>
    {% endif %}
    <div class="row">
        <br>
        <a href="{% url 'projects:radnik-add' %}">
            <button type="button" class="btn btn-success">
                <span class="glyphicon glyphicon-plus"></span>&nbsp; Dodaj radnika
            </button>
        </a>
        <a href="{% url 'projects:zanimanje-add' %}">
            <button type="button" class="btn btn-warning">
                <span class="glyphicon glyphicon-plus"></span>&nbsp; Dodaj zanimanje
            </button>
        </a>
        <a href="{% url 'projects:biranje_meseca' %}" style="float: right">
            <button type="button" class="btn btn-warning">
                <span class="glyphicon glyphicon-calendar"></span>&nbsp; Mesecni izvod radnika
            </button>
        </a>
    </div>
    <hr style="height:1px;border:none;color:#333;background-color:#333;" />

    {% if radnici %}
    <div class="well">
        <form method="get">
            <h4 style="margin-top: 0">Filter</h4>
            <div class="row">
                <div class="form-group col-sm-4 col-md-3">
                    {{ filter.form.zanimanja.label_tag }}
                    {% render_field filter.form.zanimanja class="form-control" %}
                </div>
                <div class="form-group col-sm-4 col-md-3">
                    {{ filter.form.dostupan.label_tag }}
                    {% render_field filter.form.dostupan class="form-control" %}
                </div>
                <div class="form-group col-sm-4 col-md-3">
                    {{ filter.form.posao.label_tag }}
                    {% render_field filter.form.posao class="form-control" %}
                </div>
                <div class="form-group col-sm-4 col-md-3">
                    {{ filter.form.ugovor_vazi_do.label_tag }}
                    {% render_field filter.form.ugovor_vazi_do class="form-control" %}
                </div>
            </div>

                <button type="submit" class="btn btn-primary">
                    <span class="glyphicon glyphicon-search"></span> Potvrdi
                </button>
        </form>
    </div>
    <hr>
    <div class='container' id="table">
        <div class="table-div">
            <table class="table">
                <thead>
                <tr>
                    <th>Ime</th>
                    <th>Zanimanja</th>
                    <th>Dostupnost</th>
                    <th>Trenutno na poslu</th>
                    <th>Satnica</th>
                    <th>Klasa</th>
                    <th>Ugovor važi do</th>
                    <th>Dana do isteka ugovora</th>
                </tr>
                </thead>
                <tbody>
                {% for radnik in filter.qs %}
                    {% if radnik.dostupan == True %}
                    <tr class="success">
                    {% else %}
                    <tr class="danger">
                    {% endif %}
                        <td><a href="{% url 'projects:radnik-detail' radnik.id %}">
                                <button type="button" class="btn btn-link">
                                    <span class="glyphicon glyphicon-user"></span>&nbsp; {{ radnik.ime }}
                                </button>
                            </a></td>
                        <td>* {% for j in radnik.zanimanja.all %}{{ j }} * {% endfor %}</td>
                        {% if radnik.dostupan == True %}
                        <td>Dostupan</td>
                        {% else %}
                        <td>Nedostupan</td>
                        {% endif %}
                        <td>{% if radnik.posao != None %}
                        <a href="{% url 'projects:posao' radnik.posao.id %}">{{ radnik.posao }}</a>
                        {% else %}
                        ---------------------
                        {% endif %}</td>
                        <td>{{ radnik.satnica }} eur</td>
                        <td>{{ radnik.klasa }}</td>
                        <td {% if radnik.dana_do_isteka_ugovora < 70 %}style="color:red"{% endif %}>{{ radnik.ugovor_vazi_do }}</td>
                        <td {% if radnik.dana_do_isteka_ugovora < 70 %}style="color:red"{% endif %}>{{ radnik.dana_do_isteka_ugovora }}</td>
                    </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>
    </div>
    <hr style="height:1px;border:none;color:#333;background-color:#333;" />
    {% endif %}
    {% if radnici_otkaz %}
    <h4>Radnici kojima je prestao radni odnos</h4>
    <div class='container' id="table">
        <div class="table-div">
            <table class="table">
                <thead>
                <tr>
                    <th>Ime</th>
                    <th>oib</th>
                    <th>Zanimanja</th>
                    <th></th>
                </tr>
                </thead>
                <tbody>
                {% for radnik in radnici_otkaz %}
                    <tr class="danger">
                        <td><a href="{% url 'projects:radnik-detail' radnik.id %}">
                                <button type="button" class="btn btn-link">
                                    <span class="glyphicon glyphicon-user"></span>&nbsp; {{ radnik.ime }}
                                </button>
                            </a></td>
                        <td>{{ radnik.oib }}</td>
                        <td>* {% for j in radnik.zanimanja.all %}{{ j }} * {% endfor %}</td>
                        <td>
                            <a href="{% url 'projects:radnik-delete' radnik.id %}">
                                <button type="button" class="btn btn-danger" onclick="clicked(event)">
                                    <span class="glyphicon glyphicon-remove"></span>&nbsp; Obriši
                                </button>
                            </a>
                        </td>
                    </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>
    </div>
{% endif %}
</div>
<script>
function clicked(e)
{
    if(!confirm('Ako obrišete radnika, obrisaće se svi dani koji su vezani za ovog radnika! Obrisati?'))e.preventDefault();
}
</script>
{% endblock %}



